type_dict = {
    '0x0': 'SHT_NULL (Section header table entry unused)',
    '0x1': 'SHT_PROGBITS (Program data)',
    '0x2': 'SHT_SYMTAB (Symbol table)',
    '0x3': 'SHT_STRTAB (String table)',
    '0x4': 'SHT_RELA (Relocation entries with addends)',
    '0x5': 'SHT_HASH (Symbol hash table)',
    '0x6': 'SHT_DYNAMIC (Dynamic linking information)',
    '0x7': 'SHT_NOTE (Notes)',
    '0x8': 'SHT_NOBITS (Program space with no data (bss))',
    '0x9': 'SHT_REL (Relocation entries, no addends)',
    '0xa': 'SHT_SHLIB (Reserved)',
    '0xb': 'SHT_DYNSYM (Dynamic linker symbol table)',
    '0xe': 'SHT_INIT_ARRAY (Array of constructors)',
    '0xf': 'SHT_FINI_ARRAY (Array of destructors)',
    '0x10': 'SHT_PREINIT_ARRAY (Array of pre-constructors)',
    '0x11': 'SHT_GROUP (Section group)',
    '0x12': 'SHT_SYMTAB_SHNDX (Extended section indeces)',
    '0x13': 'SHT_NUM (Number of defined types)',
    '0x60000000': 'SHT_LOOS',
    '0x6fffffef': 'SHT_LOSUNW/SHT_SUNW_capchain',
    '0x6ffffff0': 'SHT_SUNW_capinfo',
    '0x6ffffff1': 'SHT_SUNW_symsort',
    '0x6ffffff2': 'SHT_SUNW_tlssort',
    '0x6ffffff3': 'SHT_SUNW_LDYNSYM',
    '0x6ffffff4': 'SHT_SUNW_dof',
    '0x6ffffff5': 'SHT_SUNW_cap',
    '0x6ffffff6': 'SHT_SUNW_SIGNATURE',
    '0x6ffffff7': 'SHT_SUNW_ANNOTATE',
    '0x6ffffff8': 'SHT_SUNW_DEBUGSTR',
    '0x6ffffff9': 'SHT_SUNW_DEBUG',
    '0x6ffffffa': 'SHT_SUNW_move',
    '0x6ffffffb': 'SHT_SUNW_COMDAT',
    '0x6ffffffc': 'SHT_SUNW_syminfo',
    '0x6ffffffd': 'SHT_SUNW_verdef',
    '0x6ffffffe': 'SHT_SUNW_verneed',
    '0x6fffffff': 'SHT_HIOS/SHT_SUNW_versym/SHT_HISUNW',
    '0x70000000': 'SHT_LOPROC/SHT_SPARC_GOTDATA',
    '0x70000001': 'SHT_AMD64_UNWIND',
    '0x7fffffff': 'SHT_HIPROC',
    '0x80000000': 'SHT_LOUSER',
    '0xffffffff': 'SHT_HIUSER'
}

flag_dict = {
    '0x1': 'SHF_WRITE (Writable)',
    '0x2': 'SHF_ALLOC (Occupies memory during execution)',
    '0x3': 'SHF_WRITE (Writable) & SHF_ALLOC (Occupies memory during execution)',
    '0x4': 'SHF_EXECINSTR (Executable)',
    '0x5': 'SHF_EXECINSTR (Executable) & SHF_WRITE (Writable)',
    '0x6': 'SHF_EXECINSTR (Executable) & SHF_ALLOC (Occupies memory during execution)',
    '0x7': 'SHF_EXECINSTR (Executable) & SHF_ALLOC (Occupies memory during execution) & SHF_WRITE (Writable)',
    '0x10': 'SHF_MERGE (Might be merged) & SHF_ALLOC (Occupies memory during execution)',
    '0x12': 'SHF_MERGE (Might be merged)',
    '0x20': 'SHF_STRINGS (Contains nul-terminated strings)',
    '0x22': 'SHF_STRINGS (Contains nul-terminated strings) & SHF_ALLOC (Occupies memory during execution)',
    '0x40': 'SHF_INFO_LINK (sh_info contains SHT index)',
    '0x42': 'SHF_INFO_LINK (sh_info contains SHT index) & SHF_ALLOC (Occupies memory during execution)',
    '0x80': 'SHF_LINK_ORDER (Preserve order after combining)',
    '0x100': 'SHF_OS_NONCONFORMING (Non-standard OS specific handling required)',
    '0x200': 'SHF_GROUP (Section is member of a group)',
    '0x400': 'SHF_TLS (Section hold thread-local data)',
    '0x0ff00000': 'SHF_MASKOS (OS-specific)',
    '0x10000000': 'SHF_AMD64_LARGE',
    '0x40000000': 'SHF_ORDERED (Special ordering requirement (Solaris))',
    '0x80000000': 'SHF_EXCLUDE (Section is excluded unless referenced or allocated (Solaris))',
    '0xf0000000': 'SHF_MASKPROC (Processor-specific)'
    # can probably be extended properly...
}